### ISSUE TITLE
chat design

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#10]
Hi,

I would like to reopen this issue by attaching my design, which was already communicated in the August. 

Is that possible to release another 4.0.0dev2 that could accomplish this layout as close as possible?
![IMG_4009](https://github.com/user-attachments/assets/2ef245fc-6c2a-4e0d-b0b8-dbd235d70899)

**Comment by figoyouwei** [comment]
Yes, let's try CSS. We could even take the Human-to-machine dialog as starting point, just to simplify things.
https://github.com/figoyouwei/taipy_success/blob/main/chatbot/chat_calculator.py

Could the team make the following 3 changes?
1. user image rounded (aligning both users to the left could be done later)
2. user name text, next to the user image
3. message right below, not parallel to the box of user name and user image

**Comment by AlexandreSajus** [comment]
You need to be more specific with your request. Currently, the default chat control already has the user image rounded, the username text next to the user image, and the message right below. What do you mean by message not parallel to the box? Could you clarify your list of requests so I can send this to R&D

**Comment by AlexandreSajus** [comment]
From a video Youwei sent, the requirements are:
- Messages from all users need to be aligned on the left.
- The username should be aligned horizontally with the user image, within the message box, in bold, and the message should be right below the username.

Basically, this image:
![image](https://github.com/user-attachments/assets/5cbef9ef-fc81-41f9-a11f-90d6f8de979e)

**Comment by figoyouwei** [comment]
yes, that sketch is correct, if the alignment mode could be toggled, that would be perfect.

**Comment by AlexandreSajus** [comment]
How about this:
![image](https://github.com/user-attachments/assets/b6cbe0a0-f13c-4174-800f-9c1e2e54991c)

.css:
```css
/* left align sender block*/
.taipy-chat-sent {
    justify-content: flex-start;
}

/*sender avatar*/
.taipy-chat-sent .MuiStack-root .MuiBox-root {
    padding-top: unset;
}

/*sender user name*/
.taipy-chat-sent .MuiStack-root .MuiStack-root .MuiBox-root {
    border-radius: var(--border-radius) var(--border-radius) 0 0;
    font-size: inherit;
    background-color: var(--color-paper);
    width: 100%;
    margin-right: 0.7em;
}

/* sender message */
.taipy-chat-sent .MuiStack-root .MuiStack-root:last-child .MuiPaper-root {
    border-radius: 0 0 var(--border-radius) var(--border-radius);
    margin-right: unset;
}

/* remove sender message arrow*/
.taipy-chat-sent .MuiStack-root .MuiStack-root:last-child .MuiPaper-root:before {
    content: none;
}

/*sender avatar*/
.taipy-chat-received .MuiStack-root .MuiBox-root {
    padding-top: unset;
}

/* received user name*/
.taipy-chat-received .MuiStack-root .MuiStack-root .MuiBox-root {
    border-radius: var(--border-radius) var(--border-radius) 0 0;
    font-size: inherit;
    background-color: var(--color-paper);
    width: 100%;
}

/* received message*/
.taipy-chat-received .MuiStack-root .MuiStack-root .MuiPaper-root {
    border-radius: 0 0 var(--border-radius) var(--border-radius);
}
```

**Comment by AlexandreSajus** [comment]
For now this is only available on the develop version of taipy:
```bash
pip install git+https://github.com/Avaiga/taipy.git
```

**Comment by figoyouwei** [comment]
What am I supposed to proceed with the css above? I am using Poetry by the way. So please give more detailed instructions based on the current code, thanks.

**Comment by figoyouwei** [comment]
Say we are working on this code
https://github.com/figoyouwei/taipy_success/blob/main/chatbot/chat_calculator.py

**Comment by AlexandreSajus** [comment]
Sorry about that. My bad, I forgot which version of taipy you were using.

Stay with your version of Taipy with this code: https://github.com/figoyouwei/taipy_success/blob/main/chatbot/chat_calculator.py

Add chat_calculator.css next to the chat_calculator.py script.

In chat_calculator.css, add:
```css
.taipy-chat-sent {
    justify-content: flex-start;
}
.taipy-chat-sent .MuiStack-root .MuiStack-root .MuiBox-root:last-child {
    border-radius: var(--border-radius) var(--border-radius) 0 0;
    font-size: inherit;
    background-color: var(--color-paper);
    width: 100%;
    margin-right: 0.7em
}

.taipy-chat-sent .MuiStack-root .MuiStack-root:last-child .MuiPaper-root {
    border-radius: 0 0 var(--border-radius) var(--border-radius);
}

.taipy-chat-sent .MuiStack-root .MuiStack-root:last-child .MuiPaper-root:before {
    content: none;
}


.taipy-chat-received .MuiStack-root .MuiStack-root .MuiBox-root:last-child {
    border-radius: var(--border-radius) var(--border-radius) 0 0;
    font-size: inherit;
    background-color: var(--color-paper);
    width: 100%;
}
.taipy-chat-received .MuiStack-root .MuiStack-root:last-child .MuiPaper-root {
    border-radius: 0 0 var(--border-radius) var(--border-radius);
}
```

When you run chat_calculator.py, it should give you this:
![image](https://github.com/user-attachments/assets/6ae0d89a-a51a-4abc-a1c4-3ac3d90112c5)

I know this is not ideal. We now understand that Taipy needs many more styling options for our customers, and we are working on providing more styling options. Let me know what you think.
