### ISSUE TITLE
new chat design with 3 adjustments

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#13]
Hi,

I designed a new chat design with 3 very simple adjustments:

1. On the left side, put user name on top of user icon, this case, text "AI" on image AI
2. On the right side, put user the user icon to the right-hand side to the dialogue box.
3. On the right side, put user name on top of user icon, this case, text "Human" on image Human

Please see the picture, and I hope it is deliverable before Wednesday this week, thanks.
![chat design 0909](https://github.com/user-attachments/assets/1fabf934-fb07-4540-8aef-554f292a53f9)

**Comment by AlexandreSajus** [comment]
We created a new release to fix this issue. Please install: `pip install taipy==4.0.0.dev2`

![image](https://github.com/user-attachments/assets/a24155fe-488d-494f-a22a-0d80b03c2831)


With `main.py`:
```python
"""
@author: Youwei Zheng
@target: Issue #10
@update: 2024.09.03
"""

import taipy.gui.builder as tgb
from taipy.gui import Gui

# The user interacts with the Python interpreter
users = ["Human", "Result"]
messages: list[tuple[str, str, str]] = []

# ------------------------------
# Action function
# ------------------------------


def evaluate(state, var_name: str, payload: dict):
    # Retrieve the callback parameters
    (_, _, expression, sender_id) = payload.get("args", [])
    print(sender_id)
    print(expression)

    # Add the input content as a sent message
    messages.append((f"{len(messages)}", expression, sender_id))
    print(messages)

    # Default message used if evaluation fails
    result = "Invalid expression"
    try:
        # Evaluate the expression and store the result
        result = f"{eval(expression)}"
    except Exception:
        pass

    # Add the result as an incoming message
    messages.append((f"{len(messages)}", result, users[1]))
    print(messages)

    state.messages = messages


# ------------------------------
# Create page object
# ------------------------------

with tgb.Page() as page:
    tgb.chat(
        "{messages}",
        users=users,
        on_action=evaluate,
        sender_id="{users[0]}",
        # * In this case, always Human
    )

# ------------------------------
# Main app
# ------------------------------

if __name__ == "__main__":
    print("Starting calculator...")
    Gui(page).run(dark_mode=True)
```

And `main.css`:
```css
/* receiver order */
.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root {
    flex-direction: row-reverse;
}
/* receiver avatar */
.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root > .MuiBox-root {
    padding-top: 1em;
}
/* receiver name */
.taipy-chat-sent .MuiStack-root .MuiStack-root .MuiBox-root {
 text-align: end;
 margin-right: -36px;
 padding-right: 0;
}

/* received avatar */
.taipy-chat-received > .MuiGrid2-root > .MuiStack-root > .MuiBox-root {
    padding-top: 1em;
}

/* received user name */
.taipy-chat-received .MuiStack-root .MuiStack-root .MuiBox-root {
    margin-left: -44px;
    padding-left: 0;
}
```
