### ISSUE TITLE
datauv.asia

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#25]
Hey,

I have uploaded the code for datauv
https://github.com/figoyouwei/taipy_success/blob/main/datauv.asia/README.md

Two goals:
1. better mobile rendering
2. rendering about content while the url stays datauv.asia

uv pip is basically a much fast version of pip, so it shall work without issues. It is better than poetry.

**Comment by AlexandreSajus** [comment]
About the redirection to "About" issue. I just deployed your application using Azure: https://develop-datauv.taipy.cloud/
When I try to access it on both Desktop and Mobile, it redirects to the About page, as we want. Can you test this?

I'll try to figure out a way to get better mobile rendering with R&D, let me come back to you

**Comment by AlexandreSajus** [comment]
There is a way to put the sidebar above when you're in mobile by using in `static/css/main.css`:
```css
.sidebar {
    left: 2.0rem;
    height: auto;
    position: static !important;
}
```
<img src="https://github.com/user-attachments/assets/b6f1ea2e-9843-4d56-b99f-cbe2247e1ecb" width="250">

This should fix your issue. Let me know if you need anything else 🫡

**Comment by figoyouwei** [comment]
ok, thanks, I will try the css.

**Comment by figoyouwei** [comment]
Yes, it is much better now. Thanks for your effort. One more last thing, could you help me make the menu also a bit nicer in terms of styling? e.g. remove the underline and make the text bold white. Thanks.

**Comment by AlexandreSajus** [comment]
Sure! Add this to `main.css`:

```css
.css-tpnvp2 {
    color: #fff;
    text-decoration: none;
    font-weight: bold;
}

.css-7627tz {
    color: #fff;
    text-decoration: none;
    font-weight: bold;
}
```

![image](https://github.com/user-attachments/assets/04b57ab4-08af-4925-a6f6-4cee96d9e1a3)
