### ISSUE TITLE
no version of taipy==4.0.0.dev2

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#26]
Hey,

I pip installed taipy==4.0.0 this morning, it works fine, but the chat icon doesn't work, then I tried to pip install taipy==4.0.0.dev2

It returns this now, how to solve?
```
No solution found when resolving dependencies
Because there is no version of taipy==4.0.0.dev2 and you require taipy==4.0.0.dev2, we can conclude that your requirements are unsatisfiable.
```

**Comment by AlexandreSajus** [comment]
Can you share the code that triggers the chat icon bug? Yes, we deleted the dev versions now that Taipy 4.0 has been released

**Comment by figoyouwei** [comment]
Sure, it is this one
https://github.com/figoyouwei/taipy_success/blob/main/chatbot/pages/chat.py

Line 19: you define variable users
Line 82: you use the variable

Please fix this, I have report in about 36 hours and I will put this for on for demo.

**Comment by AlexandreSajus** [comment]
What does not work? By chat icon, do you mean the avatar of the AI? I added the image in `chatbot/icons/icon_ai.png` and it does display the image I put:
![image](https://github.com/user-attachments/assets/e7acb448-6449-49d2-be28-f0125b89e71d)

**Comment by figoyouwei** [comment]
Yes, the icon image doesn't work with 4.0.0, I am seeing this. Are you running my code with v4.0.0?
<img width="960" alt="Screenshot 2024-10-14 at 21 06 03" src="https://github.com/user-attachments/assets/405c8f09-b276-4664-92fa-06cab8796189">

**Comment by AlexandreSajus** [comment]
Here is where I put the image, then I ran main.py:
![image](https://github.com/user-attachments/assets/73cfc1ea-9dac-460d-bf86-924586c27f25)

**Comment by figoyouwei** [comment]
ok, very strange I probably gonna re-tried this tomorrow, if still not working, we might need to have a meeting tomorrow night, ok?

**Comment by AlexandreSajus** [comment]
Okay, we can schedule a meeting if you want. When are you available?

**Comment by figoyouwei** [comment]
Let's see, so the same code works for taipy 4.0.0. That's your conclusion, right?

**Comment by AlexandreSajus** [comment]
Yes

**Comment by figoyouwei** [comment]
ok, I re-installed everything with pip. Right now by my end, the it displays AI icon, but not human icon. This is what I am seeing. 
<img width="932" alt="Screenshot 2024-10-15 at 10 05 26" src="https://github.com/user-attachments/assets/58c3b564-5beb-470e-8e7f-932b9890b0dd">

The code is confirmed and committed again, please check again, thanks.
<img width="872" alt="Screenshot 2024-10-15 at 10 07 16" src="https://github.com/user-attachments/assets/b89280dc-035d-41b7-8df9-6980e49e4b47">

**Comment by AlexandreSajus** [comment]
I asked R&D, and I'll get back to you as soon as possible. There was probably a CSS change between 4.0.0.dev2 and 4.0.0 on the chat control

**Comment by figoyouwei** [comment]
Could I expect a solution by this week?

**Comment by AlexandreSajus** [comment]
Here you go:

In `main.css`:
```css
.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root {
    flex-direction: row;
}

.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root > .MuiBox-root {
    padding-top: 1em;
}

.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root > .MuiStack-root > .MuiBox-root {
    left: 35px;
    position: relative;
    padding-right:0;
    padding-left: 0;
}

.taipy-chat-sent > .MuiStack-root > .MuiStack-root {
    margin-right: -44px;
}

.taipy-chat-sent > .MuiStack-root > .MuiStack-root > .MuiPaper-root {
    margin-right: 54px;
}


.taipy-chat-received > .MuiGrid2-root > .MuiStack-root > .MuiBox-root {
    padding-top: 1em;
}


.taipy-chat-received .MuiStack-root .MuiStack-root .MuiBox-root {
    margin-left: -44px;
    padding-left: 0;
}

.taipy-part .p2 {
    padding-bottom: 0 !important;
}

/* chat main frame */
.css-taa4w6 {
    color: rgb(255, 255, 255);
    box-shadow: var(--Paper-shadow);
    background-image: none;
    padding-top: 1.0em;
    padding-bottom: 1.0em;
    padding-left: 1.0em;
    padding-right: 1.0em;
    background-color: rgb(42, 57, 77);
    transition: box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1);
    border-radius: 8px;
}
```

![image](https://github.com/user-attachments/assets/2eadf21a-4a1a-44da-884e-b4aee4a26d93)
