### ISSUE TITLE
chat-frame padding settings

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#27]
Hey,

I closed the previous icon issue and updated the code.

Now I want a finer settings for the chat-frame padding and right now it is not optimal.
<img width="797" alt="Screenshot 2024-10-21 at 10 43 21" src="https://github.com/user-attachments/assets/40da7fda-0cb4-478f-9ce1-78201c05bfa1">

1. The top padding shall be identical to bottom padding
2. The left padding shall be identical to right padding 
3. The left and right icons shall be aligned with the input-box left and right side.

I know it is quite tedious, I also want a better none-coding way to adjust those features ...

Please put the code below, thanks.
<img width="621" alt="Screenshot 2024-10-21 at 10 46 42" src="https://github.com/user-attachments/assets/46ad18cf-810d-4c92-be40-908c331f11a4">

**Comment by AlexandreSajus** [comment]
This should satisfy your requirements:
![image](https://github.com/user-attachments/assets/178e2357-1ae1-4346-9260-76cd8b5f0810)

In `main.css`:
```css
.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root {
    flex-direction: row;
}

.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root > .MuiBox-root {
    padding-top: 1em;
    padding-left: 10px;
}

.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root > .MuiStack-root > .MuiBox-root {
    left: 44px;
    position: relative;
    padding-right:0;
    padding-left: 0;
}

.taipy-chat-sent > .MuiStack-root > .MuiStack-root {
    margin-right: -44px;
}

.taipy-chat-sent > .MuiStack-root > .MuiStack-root > .MuiPaper-root {
    margin-right: 54px;
}

.taipy-chat-received > .MuiGrid2-root > .MuiStack-root > .MuiBox-root {
    padding-top: 1em;
}

.taipy-chat-received .MuiStack-root .MuiStack-root .MuiBox-root {
    margin-left: -44px;
    padding-left: 0;
}

.taipy-part .p2 {
    padding-bottom: 0 !important;
}

/* chat main frame */
.css-taa4w6 {
    color: rgb(255, 255, 255);
    box-shadow: var(--Paper-shadow);
    background-image: none;
    padding-top: 1.0em;
    padding-bottom: 1.0em;
    padding-left: 1.0em;
    padding-right: 1.0em;
    background-color: rgb(42, 57, 77);
    transition: box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1);
    border-radius: 8px;
}

.taipy-chat {
    padding-top: 10px;
    padding-bottom: 10px;
    padding-left: 15px;
    padding-right: 15px;
}
```
