### ISSUE TITLE
UI Design - Sidebar Profile Icon

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#30]
Hey,

I designed a sidebar with profile icon as shown below.
![UI Design - Sidebar Profile Icon](https://github.com/user-attachments/assets/0373949c-af50-4f53-af3e-3a464cd3f2fb)

Please work on this code as the second priority this week, thanks.
https://github.com/figoyouwei/taipy_success/blob/main/chatbot/pages/home.py

**Comment by AlexandreSajus** [comment]
Here you go:
![image](https://github.com/user-attachments/assets/7f0192fe-af8a-4b55-aa36-77a3e8171a81)

In `home.py`:
```python
"""
@author: Youwei Zheng
@target: Solved icon-display issue with Taipy v4.0.0
@update: 2024.10.21
"""

from dotenv import find_dotenv, load_dotenv

load_dotenv(find_dotenv())

from taipy.gui import Gui
from pages.home import page_home
from pages.chat import page_chat

# ------------------------------
# Main app
# ------------------------------

if __name__ == "__main__":
    print("Starting chatting with complete app...")

    gui = Gui(page=page_home, css_file="./main.css")
    partial_chat = gui.add_partial(page_chat)

    gui.run(dark_mode=True, title="Chat Demo v4.0.0")
```

In `main.css`:
```css
.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root {
    flex-direction: row;
}

.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root > .MuiBox-root {
    padding-top: 1em;
    padding-left: 10px;
}

.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root > .MuiStack-root > .MuiBox-root {
    left: 44px;
    position: relative;
    padding-right:0;
    padding-left: 0;
}

.taipy-chat-sent > .MuiStack-root > .MuiStack-root {
    margin-right: -44px;
}

.taipy-chat-sent > .MuiStack-root > .MuiStack-root > .MuiPaper-root {
    margin-right: 54px;
}

.taipy-chat-received > .MuiGrid2-root > .MuiStack-root > .MuiBox-root {
    padding-top: 1em;
}

.taipy-chat-received .MuiStack-root .MuiStack-root .MuiBox-root {
    margin-left: -44px;
    padding-left: 0;
}

.taipy-part .p2 {
    padding-bottom: 0 !important;
}

/* chat main frame */
.css-taa4w6 {
    color: rgb(255, 255, 255);
    box-shadow: var(--Paper-shadow);
    background-image: none;
    padding-top: 1.0em;
    padding-bottom: 1.0em;
    padding-left: 1.0em;
    padding-right: 1.0em;
    background-color: rgb(42, 57, 77);
    transition: box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1);
    border-radius: 8px;
}

/* chatframe padding settings */
.taipy-chat {
    padding-top: 15px;
    padding-bottom: 15px;
    padding-left: 20px;
    padding-right: 20px;
}

.taipy-chat > .MuiGrid2-root {
    padding-right: 10px;
}

.profile_name {
    margin-top: 0px;
}

.profile_image {
    width: 100px !important;
    height: 100px;
    border-radius: 50%;
    margin-left: auto;
    margin-right: auto;
    display: block;
    margin-top: 30px;
    object-fit: cover;
}
```
