### ISSUE TITLE
Advanced watermark

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#34]
Hey,

I know I could change the content of watermark in the `run()`

I wonder whether Taipy is capable of providing more advanced watermark style such as below. Maybe not that fancy as in PS, but somehow more advanced rendering possibilities?
![1031水印](https://github.com/user-attachments/assets/7a1ac7a7-257e-4cac-ac95-2e9479a13208)

**Comment by AlexandreSajus** [comment]
Something similar can be done through CSS:

```css
.taipy-watermark {
    transform: rotate(-45deg) translate(60px, -200px) !important;
    font-size: 8em !important;
}
```

![image](https://github.com/user-attachments/assets/9662d56b-3b0a-4504-a4fa-ff46730163fe)
